version: '3.8'  # Specify the version of Docker Compose

services:
  mlops_service:  # Name of the service (you can change this to whatever name you prefer)
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this matches the Dockerfile in your project
    environment:
      - MLFLOW_TRACKING_URI=file:///mlops_project/mlruns
    volumes:
      - ./mlops_project/mlruns:/mlops_project/mlruns  # Mount the directory for MLflow tracking data
    command: python src/main.py  # Ensure this matches the main script you want to run
